### ISSUE TITLE
Request to join? 

### ISSUE THREAD

**Issue by edco59** [openventilatorregistry/OpenVentilatorRegistry#15]
Hello, I’m still learning so I couldn’t be of much help as far as building the site goes but if you need someone to do some low level work like build a document of hospital names, addresses/phone numbers, and their respective websites or anything similar I’d be more than willing to help. This is an amazingly important project so I figured despite not having skill to offer I could try and do some grunt work so you guys don’t have to. 

Thanks for all you do! Cheers

**Comment by jordan-rosenfeld** [comment]
You've been invited to join.
