### ISSUE TITLE
I can help with Front-End

### ISSUE THREAD

**Issue by Vaatik** [openventilatorregistry/OpenVentilatorRegistry#16]
I'm a junior/intermediate front-end working already full-time in my domain.

I have experience with AngularJS SCSS TypeScript JS HTML CSS Node Angular(TypeScript version) 

I'm used to work in a MVC-type environnment with AngularJS (front-end splitted in compononents, views and controllers)

**Comment by jordan-rosenfeld** [comment]
You've been invited to join.
