### ISSUE TITLE
Request to help out :) 

### ISSUE THREAD

**Issue by billzyc** [openventilatorregistry/OpenVentilatorRegistry#17]
Hi, 
I am currently working full time as a junior developer and I have experience in UI and API development with a background in applied mathematics and physics.

This project sounds really meaningful and I would love to have an opportunity to make some contributions! 

I am experienced with JavaScript, TypeScript, Python, ReactJs, NodeJS, Sass and HTML/CSS. I am familiar with C++, Angular, and Django.  If there are appropriate tasks for me, let me know so we can discuss this opportunity further! :)

**Comment by jordan-rosenfeld** [comment]
You've been invited to join.
