### ISSUE TITLE
Request to join

### ISSUE THREAD

**Issue by 7Pass** [openventilatorregistry/OpenVentilatorRegistry#2]
Hi team,

I have 10+ years of experience with .NET. At work, I'm leading a scientific project with .NET Framework on the backend and React on the front-end. We're in progress of upgrading our project to .NET Core so I'm also familiar with .NET core.
The project uses React for front-end so React would be very familiar. I'm also using Vue.js for my personal project so I can also do Vue.js. I'm using TypeScript for all projects but Javascript is fine as well.

Let me know if I can help in anyway.

**Comment by jlm451** [comment]
I'd also be interested in contributing. My strongest area is API development (mostly on the JVM platform, but I've worked with C# too), and I'm also good with pipelines and automated acceptance testing. The web applications I contribute to at work mostly have React UIs, and I've used Vue.js in personal projects.

Feel free to let me know if any of those skills would be useful.

**Comment by jordan-rosenfeld** [comment]
You've both been invited to join.
