### ISSUE TITLE
Request to join

### ISSUE THREAD

**Issue by dannymcgee** [openventilatorregistry/OpenVentilatorRegistry#20]
Would love to volunteer my time to this. I have around 9 years of experience as a front-end UI developer/designer working with HTML and CSS. I'm currently a full-time Angular developer focusing on UI/UX and have deep Angular knowledge, but I know enough React that I'd be able to ramp up fairly quickly if that ends up being the chosen front-end tech. Zero experience with Vue. Not interested in squabbling about the stack but I would definitely be more useful in an Angular project. Just let me know how/if I can be helpful.

**Comment by jordan-rosenfeld** [comment]
You've been invited to join.
