### ISSUE TITLE
Org: Request to Collaborate

### ISSUE THREAD

**Issue by samuelzapote** [openventilatorregistry/OpenVentilatorRegistry#21]
**Purpose**
Request to join

**Details:**
I believe I can be of an asset towards the goal of this open source software. Currently working for a consulting firm. With 5 years of experience in web development, 4 of those being in Software Engineering. I have experience working with full stacks using Python and Node for backends. My strength and what I believe I could bring to the table is my project management experience as well as my experience building PWAs using the latest versions of Angular. 

Let me know if any further information is required. My LinkedIn can be found [here](https://www.businessinsider.com/coronavirus-russia-doctors-say-government-is-covering-up-cases-2020-3?r=MX&IR=T).

**Comment by jordan-rosenfeld** [comment]
You've been invited to join.
