### ISSUE TITLE
Request to Join: UI and Front End & Medical Ideas

### ISSUE THREAD

**Issue by spritefullake** [openventilatorregistry/OpenVentilatorRegistry#22]
I have experience with using medical software and contacts with medical professionals, so I hope I can help volunteer ideas also.

I have experience in buildings apps with React, React Native, JS + CSS and the Elm Architecture. On the .NET side I am very comfortable with F#. Very passionate about front-end work.

**Comment by jordan-rosenfeld** [comment]
You've been invited to join.
