### ISSUE TITLE
Request to Join

### ISSUE THREAD

**Issue by wintercarver** [openventilatorregistry/OpenVentilatorRegistry#3]
After reading the same article you reference, I wrote up a brief spec and I submitted a similar project here:
https://helpwithcovid.com/projects/279-ventilator-surveillance-platform

I'm a data scientist by training and have worked as a product manager in startup environments. Can try to offer help on the PM side or general management help. Have contacted the author of NYT article for feedback on above proposal. Open to brain storming ideas around the simplest MVP that gets an open index of supply and demand in place.

**Comment by jordan-rosenfeld** [comment]
You've been invited.
