### ISSUE TITLE
Request to Join - Full Stack (.NET C#, React, SQL) 

### ISSUE THREAD

**Issue by ml25** [openventilatorregistry/OpenVentilatorRegistry#30]
Hi! My name is Michael and I’m very interested in assisting with this project. I’m very passionate about software and I’ve always wanted to find a project where I can contribute my skill set to help others and make a positive impact on the world. I have over 7 years of full stack development experience primarily working with .NET and C# (.NET CORE included). The past two years, I have been working with React and React Native. Additionally, I’m very comfortable with SQL and NoSql databases. I’m excited for this opportunity and I’m confident my work ethic and experience would make me a valuable asset to get this project launched. LETS DO THIS!

**Comment by jordan-rosenfeld** [comment]
You have been invited to join.
