### ISSUE TITLE
Microservices with REST APIs

### ISSUE THREAD

**Issue by JKleinne** [openventilatorregistry/OpenVentilatorRegistry#36]
Hi,

I’m hoping to be able to contribute. My experience lies mostly in Back End dev with JS (node, react, express, etc.) but am flexible enough to conform according to the needs.

I could tackle the creation of the REST APIs if need be. I could also handle the deployment of the project on Google Cloud and ensure that it will scale as needed, should the traffic require it.

**Comment by chase-moskal** [comment]
how do you feel about a json-rpc interface?

#13

**Comment by jordan-rosenfeld** [comment]
You have been invited to join.
