### ISSUE TITLE
Request to join: UI and API

### ISSUE THREAD

**Issue by elliotwesoff** [openventilatorregistry/OpenVentilatorRegistry#38]
Hello,

I'd love to help if my skills can be put to use. I've been doing web dev for 6 years and I have a pretty solid repertiore with modern tech stacks. I like doing both front and back end development, so I'm ready to help wherever it's needed in those areas.

My resume is online at https://elliotwesoff.github.io, if you'd like details on what I'm familiar with (yes I know it needs to be styled). I'm currently working 40 hours a week but I will absolutely spare my off-hours if it means helping save lives. Feel free to contact me any time.

Elliot

**Comment by jordan-rosenfeld** [comment]
You have been invited.
