### ISSUE TITLE
Join request: UI/API

### ISSUE THREAD

**Issue by jonathandannel** [openventilatorregistry/OpenVentilatorRegistry#39]
I'm not currently working and I'm itching to do something meaningful while stuck indoors. 

I have a good amount of experience with React/Redux and the front end JavaScript ecosystem as a whole, as well as lots of experience with Node. I also know Python and am not scared of the back end. 

I'm willing to help wherever possible.

**Comment by aguitto** [comment]
I can help you with a mobile app in Flutter/Dart if you need

**Comment by cafeTechne** [comment]
I am willing to help as well. Where do we begin?

**Comment by jordan-rosenfeld** [comment]
You've all been invited.
