### ISSUE TITLE
Join request: UI API

### ISSUE THREAD

**Issue by Foxhunt** [openventilatorregistry/OpenVentilatorRegistry#40]
I'm offering my help on frontend matters. 

I usually build things with next.js (react) and host them on now by Zeit. Backend Logic can be done there as well. Hosting for OSS Projekts is free of cost. 

 I do not have any .net experience, i can however offer help with in JavaScript/node matter. 

Feel free to reply or send me a message.

**Comment by jordan-rosenfeld** [comment]
You have been invited to join.
