### ISSUE TITLE
Request to join: UI or API

### ISSUE THREAD

**Issue by justinchung** [openventilatorregistry/OpenVentilatorRegistry#42]
Hi,

I have experience developing REST APIs in Java, Node and UI in Javascript, React. Do not have .NET experience, but would love to help out where I can.

Justin

**Comment by justinchung** [comment]
I’m working 40 hours a week, but can dedicate time during after hours to contribute for a good cause.

**Comment by jordan-rosenfeld** [comment]
You have been invited to join.
