### ISSUE TITLE
Communication channels?

### ISSUE THREAD

**Issue by jtv199** [openventilatorregistry/OpenVentilatorRegistry#43]
I couldn't find any communication channels for now so here is a temporary discord until something more permanent gets put up. Everyone is welcome to join

https://discord.gg/vSEJdTp

**Comment by chase-moskal** [comment]
finally! nerds man, it's like herding cats! i joined :+1:

**Comment by jtv199** [comment]
Still waiting for the chief organiser to get here ;/

**Comment by mulhollen** [comment]
@jtv199 , @chase-moskal - created a slack you both should be invited with your github emails

**Comment by mulhollen** [comment]
#50 - OpenVentilatorRegis@Slack.com

**Comment by jordan-rosenfeld** [comment]
@mulhollen Hold on to your channel as we can use it for one of the teams, but for now the central channel for the organization as a whole can be found below.  The homepage has been updated.

https://join.slack.com/t/ovr-project/shared_invite/zt-d0qld5rq-RDeKgJPyIALLeiwW05fNZA
