### ISSUE TITLE
Join request: UI/Frontend

### ISSUE THREAD

**Issue by t-kaufmann** [openventilatorregistry/OpenVentilatorRegistry#46]
I‘m here to offer my skills for this project. 
I have extensive experience with front end development, in particular with Angular and JavaScript related frameworks as well as with PHP. 
I mostly use FireBase or NodeJS in the backend but I‘m comfortable with any REST API.

**Comment by t-kaufmann** [comment]
Me being a student and locked down in quarantine right now I can probably dedicate a lot of time to this :D

**Comment by jordan-rosenfeld** [comment]
You have been invited to join.
