### ISSUE TITLE
Join request: full stack

### ISSUE THREAD

**Issue by chelseyeslehc** [openventilatorregistry/OpenVentilatorRegistry#49]
I would love to help in any way that I can — I have experience with Javascript, Node/Express, React/Redux, Electron, relational/non-relational databases, HTML/CSS/SASS.

If you want a place where contributors/volunteers can communicate, I can also setup a Slack workspace and see if we could get approval for a comp paid plan.

**Comment by jordan-rosenfeld** [comment]
You have been invited to join.
