### ISSUE TITLE
SLACK - OpenVentilatorRegistry - Please join

### ISSUE THREAD

**Issue by mulhollen** [openventilatorregistry/OpenVentilatorRegistry#50]

**Comment by mulhollen** [comment]
OpenVentilatorRegis@slack.com

**Comment by jordan-rosenfeld** [comment]
We can use this channel for one of the teams, but for now the organization as a whole is centralizing around the channel below:

https://join.slack.com/t/ovr-project/shared_invite/zt-d0qld5rq-RDeKgJPyIALLeiwW05fNZA
