### ISSUE TITLE
Join Request: API/Database

### ISSUE THREAD

**Issue by ngearhart** [openventilatorregistry/OpenVentilatorRegistry#54]
Hello,
I would like to join the organization as either an API or Database developer.
I have extensive experience developing with ASP.NET (Legacy .NET Framework), and I can learn quickly so I am confident in my ability to write for .NET Core.
I also have a good bit of experience using ORMs (specifically Django), so if we choose that route, I can be helpful.

To view a full list of details about my experience, and to find more information about me, you can check out my website (which includes my resume) at [noahgearhart.com](https://noahgearhart.com).

I would like to join this project because I want to give back to the community somehow related to the COVID-19 outbreak. In the words of one of my professors, "it's a great time to be a computer scientist," and I want to take advantage of the opportunity to help out.

Thank you for your consideration!

**Comment by jordan-rosenfeld** [comment]
You have been invited to join.
