### ISSUE TITLE
Request to join

### ISSUE THREAD

**Issue by SamIAmHarris** [openventilatorregistry/OpenVentilatorRegistry#60]
I am mainly a mobile dev. Most of my experience is in Android but have helped out Node.js backends before.

Though I do not have much web experience, I think I could ramp up quickly and help out on UI side. I would be open to do QA if my lack of web experience is an issue. And can also help out with PM during normal work hours.

**Comment by jordan-rosenfeld** [comment]
You have been invited to join.
