### ISSUE TITLE
Join request: UI/UX

### ISSUE THREAD

**Issue by alekexe** [openventilatorregistry/OpenVentilatorRegistry#62]
Hello I am a experienced frontend website developer.

I am a student in quarantine so I have **a lot** of free time.
My timezone is CET but I am willing to change my sleeping schedule if that is needed.

This is a great project and I would LOVE to work with you guys to help everybody and make a world a better place. 
Best regards. :)

**Comment by jordan-rosenfeld** [comment]
You have been invited to join.
