### ISSUE TITLE
Slack, trello, discord?

### ISSUE THREAD

**Issue by jonathandannel** [openventilatorregistry/OpenVentilatorRegistry#67]
So it's been a while now and numerous people have been added to the project but there's no clear direction going on for how contributors can actually, well, contribute.

Can we get something going where we can track our progress and delegate tasks?

**Comment by BPerry24** [comment]
https://github.com/openventilatorregistry/OpenVentilatorRegistry/blob/master/README.md#central-communication-channel

**Comment by jordan-rosenfeld** [comment]
Thanks @BPerry24 :)
