### ISSUE TITLE
Wireframe: Profile Pages

### ISSUE THREAD

**Issue by wintercarver** [openventilatorregistry/OpenVentilatorRegistry#68]
Both Hospitals and Businesses will have a profile page. We can try to be simple and recycle as much as possible across them:
* Name of establishment 
* Contact Address
* Contact e-mail
* Contact phone number 
* Timestamp of last update
* Table view with history of updates (column details will differ between hospital vs business)

* a "Contact Profile Owner" function: interaction to allow a profile viewer to contact the profile owner. See section "Contact Flow" in the spec (https://docs.google.com/document/d/12BtP4gwri7fRKUiedzYkyQuKYWt7gbXLqpzErgVRv7g/edit#). 

* a "Add New Status" function: modal-based workflow (or whatever is easiest?) to add the new status of the hospital or business. Output is to add a new row to the table view of the status history. Most recent row at top. 

* Status history table: delete/edit row functionality. 

Note: editing a row can have odd implications for timestamps on backend data structure. We want explicit "created_at" and "edited_at" and "deleted_at" fields per row.

**Comment by wintercarver** [comment]
@supernoir, the registration flow should conclude with landing the registered user on their profile page of their establishment (hospital or business). 

For the Profile Owner, when they view their profile they should see their full contact card and status history table. If we decouple the status entry from the registration flow (comments in Figma mocks on that), then there will be an empty state initially that should prompt status entry. Entry of status is optional, for now.

**Comment by supernoir** [comment]
Thanks for your input, I will add this to the story in the UI project: 
https://github.com/openventilatorregistry/Design/issues/7
https://github.com/openventilatorregistry/Design/issues/15
