### ISSUE TITLE
Backend proposal

### ISSUE THREAD

**Issue by 0x62** [openventilatorregistry/OpenVentilatorRegistry#7]
I've been using [Hasura](https://hasura.io/) recently. It allows you to deploy a full production GraphQL API off a database structure (with access control). I believe the requirements for this project could be easily accomplished with this, and would reduce the backend development time. 

UI could then be generated with React Admin off the schema.

Thoughts?

**Comment by jordan-rosenfeld** [comment]
You've been invited to join the backend team.
